"""
CEO Briefing System — Weekly Executive Summary Generator
Runs every Sunday night. Reads Business_Goals.md, /Done tasks, finance data.
Generates: /Vault/Briefings/YYYY-MM-DD_Monday_Briefing.md

Includes:
- Revenue summary
- Bottleneck analysis
- Missed deadlines detection
- AI-generated suggestions (cost savings, improvements)
- Task performance metrics
- Upcoming week priorities
"""

import json
import re
from pathlib import Path
from datetime import datetime, timezone, timedelta
from typing import Optional

from config import config, FOLDERS, ensure_folders
from logger_setup import logger, audit_log
from scripts.goal_tracker import GoalTracker


class CEOBriefing:
    """Generates weekly CEO briefing documents."""

    def __init__(self):
        ensure_folders()
        self.goals_tracker = GoalTracker()
        self.briefings_folder = FOLDERS["briefings"]

    def generate_briefing(self, date: datetime | None = None) -> str:
        """
        Generate a full CEO briefing document.
        Returns the path to the generated file.
        """
        if date is None:
            date = datetime.now(timezone.utc)

        # Next Monday's date for briefing title
        days_until_monday = (7 - date.weekday()) % 7 or 7
        monday_date = date + timedelta(days=days_until_monday)
        monday_str = monday_date.strftime("%Y-%m-%d")

        briefing_file = self.briefings_folder / f"{monday_str}_Monday_Briefing.md"

        logger.info(f"CEO Briefing: Generating briefing for week of {monday_str}")
        audit_log(
            action="ceo_briefing_generated",
            details={"week": monday_str, "file": str(briefing_file)},
        )

        # Gather all data sections
        goals = self.goals_tracker.load()
        revenue_summary = self._generate_revenue_summary(goals)
        task_metrics = self._generate_task_metrics()
        bottlenecks = self._analyze_bottlenecks(goals)
        missed_deadlines = self._detect_missed_deadlines(goals)
        finance_summary = self._generate_finance_summary()
        ai_suggestions = self._generate_ai_suggestions(goals, task_metrics, finance_summary)
        upcoming_priorities = self._determine_upcoming_priorities(goals)
        business_health = self.goals_tracker.get_overall_health()

        # Build briefing markdown
        content = f"""---
type: ceo_briefing
week_of: {monday_str}
generated: {datetime.now(timezone.utc).isoformat()}
business_health: {business_health}
generated_by: AI Employee v1.0 (Gold Level)
---

# 📊 CEO Weekly Briefing — Week of {monday_str}

> **Generated:** {datetime.now(timezone.utc).strftime("%A, %B %d, %Y at %I:%M %p UTC")}
> **Business Health:** {business_health}
> **Classification:** Confidential — CEO Eyes Only

---

## 🏢 Executive Summary

"""
        content += self._executive_summary(business_health, revenue_summary, task_metrics, bottlenecks)

        content += f"""
---

## 💰 Revenue Summary

{revenue_summary}

---

## 📈 Task & Performance Metrics

{task_metrics}

---

## ⚠️ Bottleneck Analysis

{bottlenecks}

---

## 🚨 Missed Deadlines

{missed_deadlines}

---

## 💸 Finance Summary

{finance_summary}

---

## 🤖 AI Recommendations

{ai_suggestions}

---

## 🎯 Priorities for This Week

{upcoming_priorities}

---

## 📋 Action Items for CEO

{self._generate_action_items(bottlenecks, missed_deadlines, ai_suggestions)}

---

## 📎 Appendix

### Data Sources
- Business Goals: `{config.business_goals_path}`
- Completed Tasks: `{FOLDERS['done']}`
- Finance State: `{FOLDERS['logs'] / 'finance_state.json'}`
- Audit Log: `{FOLDERS['logs'] / 'audit.jsonl'}`
- Task Logs: `{FOLDERS['logs'] / 'tasks/'}`

### System Metrics
- Total Tasks Processed (this week): {task_metrics.get('total_this_week', 0)}
- Success Rate: {task_metrics.get('success_rate', 0):.1f}%
- Average Completion Time: {task_metrics.get('avg_time', 'N/A')}
- Pending Approvals: {task_metrics.get('pending_approvals', 0)}

---

> 🤖 *This briefing was auto-generated by your Personal AI Employee.*
> *For questions or feedback, move tasks to Needs_Action with details.*
> *Next briefing will be generated next Sunday at {config.ceo_briefing_hour}:00.*
"""
        # Write briefing file
        with open(briefing_file, "w", encoding="utf-8") as f:
            f.write(content)

        # Also create a task in Inbox for the CEO to review
        self._create_review_task(monday_str, briefing_file)

        logger.info(f"CEO Briefing generated: {briefing_file}")
        return str(briefing_file)

    # ─── Section Generators ────────────────────────────────────────────

    def _executive_summary(self, health: str, revenue: str, tasks: str, bottlenecks: str) -> str:
        """Generate a 3-4 sentence executive summary."""
        # Parse key data points
        total_done = len(list(FOLDERS["done"].glob("*.md"))) if FOLDERS["done"].exists() else 0
        total_pending = len(list(FOLDERS["pending_approval"].glob("*.md"))) if FOLDERS["pending_approval"].exists() else 0

        summary_parts = [
            f"**Business Status:** {health}",
            f"**Tasks Completed (all-time):** {total_done}",
            f"**Awaiting Your Approval:** {total_pending} tasks",
        ]

        if "Critical" in health:
            summary_parts.append(
                "**Immediate attention required.** Multiple KPIs are off target. "
                "Review the bottlenecks and missed deadlines sections below."
            )
        elif "Healthy" in health:
            summary_parts.append(
                "**Business is on track.** Most KPIs are meeting targets. "
                "Focus areas this week: scaling operations and client acquisition."
            )
        else:
            summary_parts.append(
                "**Mixed performance.** Some areas need attention. "
                "Review bottleneck analysis and AI recommendations below."
            )

        return "\n\n".join(summary_parts)

    def _generate_revenue_summary(self, goals) -> str:
        """Generate revenue summary from business goals."""
        if not goals.revenue_targets:
            return "> No revenue targets defined in Business_Goals.md yet."

        content = "| Period | Target | Actual | Progress | Status |\n"
        content += "|--------|--------|--------|----------|--------|\n"

        for rt in goals.revenue_targets:
            if rt.progress_pct >= 100:
                status = "🟢 On Track"
            elif rt.progress_pct >= 50:
                status = "🟡 Behind"
            else:
                status = "🔴 At Risk"

            content += f"| {rt.period} | ${rt.target:,.0f} | ${rt.actual:,.0f} | {rt.progress_pct:.0f}% | {status} |\n"

        # Annual summary
        total_target = sum(rt.target for rt in goals.revenue_targets)
        total_actual = sum(rt.actual for rt in goals.revenue_targets)
        overall_progress = (total_actual / total_target * 100) if total_target > 0 else 0

        content += f"\n**Annual Total:** ${total_actual:,.0f} / ${total_target:,.0f} ({overall_progress:.0f}%)\n"

        if goals.revenue_targets:
            annual = goals.revenue_targets[-1]  # Last row is usually annual
            content += f"**Current Run Rate:** ${total_actual:,.0f} YTD\n"

        return content

    def _generate_task_metrics(self) -> dict:
        """Analyze task performance from vault folders."""
        now = datetime.now(timezone.utc)
        one_week_ago = now - timedelta(days=7)

        metrics = {
            "total_all_time": 0,
            "total_this_week": 0,
            "done": 0,
            "rejected": 0,
            "needs_action": 0,
            "pending": 0,
            "success_rate": 0,
            "avg_time": "N/A",
            "pending_approvals": 0,
            "by_source": {},
        }

        # Count files in each folder
        done_files = list(FOLDERS["done"].glob("*.md")) if FOLDERS["done"].exists() else []
        rejected_files = list(FOLDERS["rejected"].glob("*.md")) if FOLDERS["rejected"].exists() else []
        needs_action_files = list(FOLDERS["needs_action"].glob("*.md")) if FOLDERS["needs_action"].exists() else []
        pending_files = list(FOLDERS["pending_approval"].glob("*.md")) if FOLDERS["pending_approval"].exists() else []

        metrics["done"] = len(done_files)
        metrics["rejected"] = len(rejected_files)
        metrics["needs_action"] = len(needs_action_files)
        metrics["pending_approvals"] = len(pending_files)
        metrics["total_all_time"] = metrics["done"] + metrics["rejected"] + metrics["needs_action"]

        total_resolved = metrics["done"] + metrics["rejected"]
        metrics["success_rate"] = (metrics["done"] / total_resolved * 100) if total_resolved > 0 else 0

        # Count this week's tasks
        for f in done_files + rejected_files:
            try:
                mtime = datetime.fromtimestamp(f.stat().st_mtime, tz=timezone.utc)
                if mtime >= one_week_ago:
                    metrics["total_this_week"] += 1
            except Exception:
                pass

        # Analyze by source
        for f in done_files:
            try:
                content = f.read_text(encoding="utf-8")
                source_match = re.search(r"source:\s*(\S+)", content)
                if source_match:
                    source = source_match.group(1)
                    metrics["by_source"][source] = metrics["by_source"].get(source, 0) + 1
            except Exception:
                pass

        # Build markdown output
        md = f"""### Overall Performance

| Metric | Value |
|--------|-------|
| Total Tasks (all-time) | {metrics['total_all_time']} |
| Completed This Week | {metrics['total_this_week']} |
| Successfully Done | {metrics['done']} |
| Rejected | {metrics['rejected']} |
| Needs Action | {metrics['needs_action']} |
| **Success Rate** | **{metrics['success_rate']:.1f}%** |
| Pending Your Approval | {metrics['pending_approvals']} |

### Tasks by Source

| Source | Completed |
|--------|-----------|
"""
        for source, count in sorted(metrics["by_source"].items(), key=lambda x: -x[1]):
            md += f"| {source} | {count} |\n"

        if not metrics["by_source"]:
            md += "| None yet | 0 |\n"

        metrics["_markdown"] = md
        return metrics

    def _analyze_bottlenecks(self, goals) -> str:
        """Analyze current bottlenecks and their impact."""
        if not goals.bottlenecks:
            return "> No bottlenecks defined in Business_Goals.md.\n> Consider adding known bottlenecks for AI monitoring."

        content = "| Bottleneck | Impact | Mitigation | AI Status |\n"
        content += "|------------|--------|------------|----------|\n"

        for bn in goals.bottlenecks:
            # Check if we've created tasks related to this bottleneck
            related_tasks = 0
            if FOLDERS["done"].exists():
                for f in FOLDERS["done"].glob("*.md"):
                    try:
                        txt = f.read_text(encoding="utf-8").lower()
                        if any(kw in txt for kw in bn.description.lower().split()[:3]):
                            related_tasks += 1
                    except Exception:
                        pass

            ai_status = f"🟢 Addressed ({related_tasks} tasks)" if related_tasks > 0 else "🔴 No action taken"
            content += f"| {bn.description} | {bn.impact} | {bn.mitigation} | {ai_status} |\n"

        # Add auto-detected bottlenecks from task data
        needs_action_count = metrics_count(FOLDERS["needs_action"])
        if needs_action_count > 5:
            content += f"\n> ⚠️ **Auto-Detected:** {needs_action_count} tasks stuck in Needs_Action — "
            content += "this may indicate a systemic bottleneck in task processing.\n"

        pending_count = metrics_count(FOLDERS["pending_approval"])
        if pending_count > 3:
            content += f"\n> ⏳ **Auto-Detected:** {pending_count} tasks awaiting your approval — "
            content += "this is slowing down execution velocity.\n"

        return content

    def _detect_missed_deadlines(self, goals) -> str:
        """Detect projects with past-due target launch dates."""
        now = datetime.now(timezone.utc)
        missed = []
        at_risk = []

        for proj in goals.projects:
            if not proj.target_launch:
                continue

            try:
                target_date = datetime.strptime(proj.target_launch, "%Y-%m-%d").replace(tzinfo=timezone.utc)
                days_diff = (target_date - now).days

                if days_diff < 0:
                    missed.append({
                        "project": proj.name,
                        "deadline": proj.target_launch,
                        "days_overdue": abs(days_diff),
                        "status": proj.status,
                    })
                elif days_diff <= 7:
                    at_risk.append({
                        "project": proj.name,
                        "deadline": proj.target_launch,
                        "days_remaining": days_diff,
                        "status": proj.status,
                    })
            except (ValueError, TypeError):
                pass

        if not missed and not at_risk:
            return "✅ **No missed deadlines detected.** All project timelines are on track."

        content = ""

        if missed:
            content += f"### 🚨 Missed Deadlines ({len(missed)})\n\n"
            content += "| Project | Deadline | Days Overdue | Status |\n"
            content += "|---------|----------|-------------|--------|\n"
            for m in missed:
                content += f"| {m['project']} | {m['deadline']} | {m['days_overdue']} days | {m['status']} |\n"

        if at_risk:
            content += f"\n### ⚠️ At-Risk Deadlines ({len(at_risk)})\n\n"
            content += "| Project | Deadline | Days Remaining | Status |\n"
            content += "|---------|----------|---------------|--------|\n"
            for a in at_risk:
                content += f"| {a['project']} | {a['deadline']} | {a['days_remaining']} days | {a['status']} |\n"

        return content

    def _generate_finance_summary(self) -> str:
        """Generate finance summary from state file."""
        state_file = FOLDERS["logs"] / "finance_state.json"

        if not state_file.exists():
            return "> No finance data available yet.\n> Configure finance_watcher to track transactions."

        try:
            with open(state_file, "r") as f:
                state = json.load(f)

            known_txns = state.get("known_transactions", [])
            last_balance = state.get("last_balance", 0)
            last_check = state.get("last_check", "Never")

            content = f"| Metric | Value |\n|--------|-------|\n"
            content += f"| Known Transactions | {len(known_txns)} |\n"
            content += f"| Last Recorded Balance | ${last_balance:,.2f} |\n"
            content += f"| Last Check | {last_check} |\n"

            # Categorize transactions if available
            categories = {}
            for txn_id in known_txns[-20:]:  # Last 20
                # Simple heuristic based on ID patterns
                if "sub" in txn_id.lower() or "subscription" in txn_id.lower():
                    categories["Subscriptions"] = categories.get("Subscriptions", 0) + 1
                elif "fee" in txn_id.lower():
                    categories["Fees"] = categories.get("Fees", 0) + 1
                else:
                    categories["General"] = categories.get("General", 0) + 1

            if categories:
                content += "\n**Recent Transaction Categories:**\n"
                for cat, count in categories.items():
                    content += f"- {cat}: {count}\n"

        except Exception as e:
            content = f"> Error reading finance data: {e}"

        return content

    def _generate_ai_suggestions(self, goals, task_metrics: dict, finance_summary: str) -> str:
        """Generate AI-powered suggestions for cost savings and improvements."""
        suggestions = []

        # Cost savings suggestions
        suggestions.append("### 💰 Cost Savings Opportunities\n")

        # Check for duplicate subscriptions
        suggestions.append(
            "1. **Audit Subscriptions** — Review all active subscriptions for duplicates or unused services. "
            "Estimated savings: 10-15% of software spend."
        )

        # AI automation suggestions
        success_rate = task_metrics.get("success_rate", 0)
        if success_rate < 90:
            suggestions.append(
                f"2. **Improve AI Task Success Rate** — Current rate is {success_rate:.1f}%. "
                f"Analyze rejected tasks to identify patterns. "
                f"Each failure represents manual rework cost."
            )
        else:
            suggestions.append(
                f"2. **Maintain AI Performance** — Success rate at {success_rate:.1f}%. "
                f"Consider expanding AI scope to new task types."
            )

        # Process optimization
        pending = task_metrics.get("pending_approvals", 0)
        if pending > 0:
            suggestions.append(
                f"3. **Streamline Approvals** — {pending} tasks awaiting approval. "
                f"Consider auto-approving low-risk actions to increase throughput."
            )

        # Revenue suggestions based on goals
        for rt in goals.revenue_targets:
            if rt.progress_pct < 50:
                suggestions.append(
                    f"4. **Accelerate {rt.period} Revenue** — Only {rt.progress_pct:.0f}% of ${rt.target:,.0f} target achieved. "
                    f"Consider launching targeted campaign or adjusting pricing."
                )
                break

        # Bottleneck-based suggestions
        for bn in goals.bottlenecks:
            if "onboarding" in bn.description.lower():
                suggestions.append(
                    f"5. **Automate Client Onboarding** — Current 3-day process can be reduced to 30 minutes "
                    f"with AI-generated welcome packets and automated setup."
                )

        # Improvement suggestions
        suggestions.append("\n### 🚀 Strategic Improvements\n")

        if not goals.projects:
            suggestions.append(
                "1. **Define Active Projects** — No projects tracked in Business_Goals.md. "
                "Add projects for AI to monitor and report on."
            )

        for initiative in goals.strategic_initiatives[:3]:
            suggestions.append(f"- **{initiative}**")

        return "\n\n".join(suggestions)

    def _determine_upcoming_priorities(self, goals) -> str:
        """Determine priorities for the coming week."""
        priorities = []

        # Check at-risk projects
        now = datetime.now(timezone.utc)
        for proj in goals.projects:
            if proj.status in ["In Progress", "Planning"] and proj.target_launch:
                try:
                    target = datetime.strptime(proj.target_launch, "%Y-%m-%d").replace(tzinfo=timezone.utc)
                    days_left = (target - now).days
                    if 0 <= days_left <= 14:
                        priorities.append(f"🔴 **{proj.name}** — Launch in {days_left} days (Priority: {proj.priority})")
                    elif 14 < days_left <= 30:
                        priorities.append(f"🟡 **{proj.name}** — Launch in {days_left} days (Priority: {proj.priority})")
                except (ValueError, TypeError):
                    pass

        # Check quarterly goals
        for quarter, quarter_goals in goals.quarterly_goals.items():
            unchecked = [g for g in quarter_goals if not g.startswith("[x]")]
            if unchecked:
                priorities.append(f"📋 **{quarter}** — {len(unchecked)} goals remaining")

        if not priorities:
            return "No urgent priorities identified. Focus on steady operations and growth initiatives."

        return "\n\n".join([f"{i+1}. {p}" for i, p in enumerate(priorities)])

    def _generate_action_items(self, bottlenecks: str, deadlines: str, suggestions: str) -> str:
        """Generate concrete action items for the CEO."""
        items = []

        # From bottlenecks
        if "🔴" in bottlenecks:
            items.append("Review and address red-flag bottlenecks")

        # From deadlines
        if "Missed" in deadlines or "Overdue" in deadlines:
            items.append("Reschedule or reassess missed project deadlines")

        # From suggestions
        if "Cost Savings" in suggestions:
            items.append("Review cost savings opportunities")

        # Always include
        items.append("Review pending approvals queue")
        items.append("Update Business_Goals.md if strategy has changed")

        if not items:
            items.append("No critical action items — continue current operations")

        content = "| # | Action Item | Priority | Status |\n"
        content += "|---|-------------|----------|--------|\n"
        for i, item in enumerate(items, 1):
            content += f"| {i} | {item} | {'🔴' if i <= 2 else '🟡'} | [ ] |\n"

        return content

    def _create_review_task(self, monday_str: str, briefing_path: Path):
        """Create a task in Inbox for the CEO to review the briefing."""
        task_id = f"BRIEFING_{monday_str.replace('-', '')}"
        task_file = FOLDERS["inbox"] / f"{task_id}.md"

        content = f"""---
task_id: {task_id}
source: ceo_briefing
created: {datetime.now(timezone.utc).isoformat()}
status: inbox
priority: high
briefing_path: {briefing_path}
---

# 📊 Review Weekly CEO Briefing

**Week of:** {monday_str}
**Generated:** {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}

## Briefing Document
Open: `{briefing_path}`

## Action Required
> [!REVIEW] Read the weekly briefing and:
> - Update Business_Goals.md if strategy changed
> - Approve/reject AI recommendations
> - Address any missed deadlines
> - Clear pending approvals queue
"""
        with open(task_file, "w", encoding="utf-8") as f:
            f.write(content)

        logger.info(f"CEO Briefing: Review task created: {task_id}")


# ─── Helper ────────────────────────────────────────────────────────────

def metrics_count(folder: Path) -> int:
    """Count .md files in a folder."""
    if not folder.exists():
        return 0
    return len(list(folder.glob("*.md")))


# ─── Module-level convenience ─────────────────────────────────────────

def generate_ceo_briefing(date: datetime | None = None) -> str:
    """One-shot briefing generation."""
    briefing = CEOBriefing()
    return briefing.generate_briefing(date)


if __name__ == "__main__":
    briefing = CEOBriefing()
    path = briefing.generate_briefing()
    print(f"\n✅ CEO Briefing generated: {path}")
